### ISSUE TITLE
Manifest URL Change Notice

### ISSUE THREAD

**Issue by Armandeus66** [robinsving/pf2e-item-revitalizer#10]
Recently each time I check for module updates, this module asks to update the manifest (correct term?) URL. It then shows that it has not upgraded to a new version number. Today it asked and went from 1.4.0 to 1.4.0.

**Comment by robinsving** [comment]
That sounds annoying. I had some issues handling the versioning from Foundry's module handling system.

I had hoped that the latest version had fixed that (it worked for me), so could you try to reinstall the module and see what happens then?

**Comment by ElroTheOnk** [comment]
I have the same problem. Just tried a simple uninstall/reinstall from inside Foundry -> Add-on Modules & still get the same issue when clicking Update All.

**Comment by ElroTheOnk** [comment]
![image](https://github.com/robinsving/pf2e-item-revitalizer/assets/1310418/4f162bf5-5442-4dbc-9d60-c048530fa3dd)

**Comment by Armandeus66** [comment]
Same here. The URL is different but the version number is the same.

**Comment by robinsving** [comment]
I will check once I am back home in a few days. Hopefully it is something you can live with until then

**Comment by ElroTheOnk** [comment]
> I will check once I am back home in a few days. Hopefully it is something you can live with until then

Absolutely, this is a QoL issue, not fundamental! I love the idea of this module, so thanks very much; just chipping in in the hope of 1) encouraging you that people do indeed use it (& like it!); and 2) providing any help I can to pin down :)

**Comment by robinsving** [comment]
I have made the update so that the 1+ version matches the 1.4.0. I am not sure if this is the correct setup, but I am not getting the issue after a reinstall. Could either of you check if it works for you now?

**Comment by ElroTheOnk** [comment]
Hi - thanks very much. Initial signs very promising, just ran an Update All (without uninstalling/reinstalling) and no more "sidegrade" manifest URL popup, so looks like it works :)

**Comment by robinsving** [comment]
I pushed a few minors for testing, and after 1.5.2 it works for me again. Please have a check @Armandeus66
