### ISSUE TITLE
Feature Request: Ignore ChoiceSet by default

### ISSUE THREAD

**Issue by shandrakor** [robinsving/pf2e-item-revitalizer#11]
The ChoiceSet RE modifies itself on execution to store the selected choice. As a result, any feat or feature with a ChoiceSet will always pop up as modified rules. There may be occasions where the feature's rule also ACTUALLY changed, so maybe put a toggle in the settings to say whether you want to examine ChoiceSet REs, and default to no.

**Comment by robinsving** [comment]
That is very interesting. It does not do that for me using the latest version. The Item I am testing with is the Methodology for the Investigator, which properly ignores "selection".
Can you send me information of the Item you are looking at, as well as the version of PIR that you are running?

**Comment by shandrakor** [comment]
Never mind, call this a no repro. Perhaps this was an issue in the past, but when I dug deeper on all the examples I could find with my current actors, they all featured changes, if frequently very small ones.
