### ISSUE TITLE
Remaster System Updates to spell damage are not recognized

### ISSUE THREAD

**Issue by sorrythatuserbla** [robinsving/pf2e-item-revitalizer#14]
E.g. Electric Arc: 
It only tells you that the "Description" is different. In fact the damage is different also. Attribute Modifier to damage is gone. Instead there is a die more.
Same for all these spells.

**Comment by robinsving** [comment]
I just noticed the same thing. After Remaster the damage value is completely empty. Investigating

**Comment by robinsving** [comment]
The damage used to include value, is now an array. Fix is out shortly

**Comment by robinsving** [comment]
1.14.1 fixed this, but I realized that the Remaster changed the structure quite massively, so I will make some bigger issues for that
