### ISSUE TITLE
system version error

### ISSUE THREAD

**Issue by cyanogreen** [robinsving/pf2e-item-revitalizer#15]
Cant enable it post remaster because it says it is incompatible
![image](https://github.com/robinsving/pf2e-item-revitalizer/assets/151007670/d87d0d8b-ef52-47c8-adcb-9391a40d0654)

**Comment by robinsving** [comment]
Yes. The remaster rewrote the Item structure in a big way. 1.15+ will get some adjustments, but it will have to wait until this weekend, sorry

**Comment by robinsving** [comment]
1.15.0 is out now, please have a look

**Comment by cyanogreen** [comment]
works perfectly now, thank you
