### ISSUE TITLE
acBonus false positive

### ISSUE THREAD

**Issue by this-gavagai** [robinsving/pf2e-item-revitalizer#16]
This is such an awesome module. On behalf of my entire table, thank you so much for the work you've put into it.

I think I'm getting a false positive for acBonus when potency runes are applied to armor. To Hit bonuses seem to get ignored when potency runes are applied to weapons, so I'm assuming this is indeed a false positive and not just intended behavior, but I definitely might be misunderstanding the intended workflow.

If there is anything I can do to help troubleshoot, please let me know. The reproduction steps seem pretty simple: 
- Add new armor from compendium to character sheet
- Edit armor and add potency rune +1
- Invest armor (doesn't trigger, notably, if the armor isn't invested)
- Run Revitalize

**Comment by robinsving** [comment]
Can you give 1.18.0 a try and see if that solves it for you?

**Comment by this-gavagai** [comment]
Yes, it's working great! Thanks so much. Your module is a huge contribution to Foundry, and my investigator who recently acquired a much-more-automated Devise a Strategem in particular thanks you!
