### ISSUE TITLE
Restore the list of items that require manual recreation

### ISSUE THREAD

**Issue by Vesselchuck** [robinsving/pf2e-item-revitalizer#17]
I'm having difficulty grasping the implications of this change. Could you kindly clarify how one is expected to be aware of the need to manually recreate any items when the module no longer displays them?
![Screenshot_1](https://github.com/robinsving/pf2e-item-revitalizer/assets/70449411/a9c4882f-5dc9-4575-82b1-1c9fa6fca2f9)

**Comment by robinsving** [comment]
I am not sure that you mean. The "*" is an asterisk, anything marked with the asterisk is one that requires manual recreation.
Did you perhaps not have a single of the annoying properties in the results page?

Can you perhaps provide a fuller screenshot, and I will see if I can help you further

**Comment by Vesselchuck** [comment]
> I am not sure that you mean. The "*" is an asterisk, anything marked with the asterisk is one that requires manual recreation. Did you perhaps not have a single of the annoying properties in the results page?
> 
> Can you perhaps provide a fuller screenshot, and I will see if I can help you further

![image](https://github.com/robinsving/pf2e-item-revitalizer/assets/70449411/13b50a92-f311-467b-bff3-2fd99e675985)
Sure, here's the example of what I mean.

**Comment by robinsving** [comment]
Any suggestions on how the term can be more clear? Something like this perhaps:

> Any property marked with an asterisk (*) will require a manual recreation, and will be skipped during Revitilization

**Comment by Vesselchuck** [comment]
> Any suggestions on how the term can be more clear? Something like this perhaps:
> 
> > Any property marked with an asterisk (*) will require a manual recreation, and will be skipped during Revitilization

I am still uncertain about the significance of the asterisk. I initially thought it indicated that items included in previous versions of the module, which now require manual recreation, are simply omitted from the list.

Personally, I haven't come across any items with an asterisk. It's possible that the characters I used the Revitalizer module don't have any such items. However, I find it peculiar that this text appears at all then. Could you provide further insight into this matter? Thank you.

**Comment by robinsving** [comment]
This is the same reason that the built-in "Refresh" fro the most recent PF2e system version doesn't work sometimes, the logic to update is too advanced when it comes to things like Rule Engine differences, for instance. Also, a lot of spells will have this for Damage, Overlays, and Hightening.
I don't want anyone's Items to be ruined, so I do the same thing as the PF2e devs.

There needs to be some information to clear up why things are as they are, but I get that there will be confusion when a text appears and references nothing. I guess I could hide it when there are no such Items instead.

**Comment by Vesselchuck** [comment]
> This is the same reason that the built-in "Refresh" fro the most recent PF2e system version doesn't work sometimes, the logic to update is too advanced when it comes to things like Rule Engine differences, for instance. Also, a lot of spells will have this for Damage, Overlays, and Hightening. I don't want anyone's Items to be ruined, so I do the same thing as the PF2e devs.
> 
> There needs to be some information to clear up why things are as they are, but I get that there will be confusion when a text appears and references nothing. I guess I could hide it when there are no such Items instead.

I understand the challenge with that, especially with Rule Elements. It's commendable that you're cautious to avoid any impact on users' items.

Considering the potential for confusion, hiding the text when no relevant items are present seems like a practical solution. Thanks for your efforts in addressing the issue!

**Comment by robinsving** [comment]
1.20.1 should have what you need
