### ISSUE TITLE
Feature request : Add the "Refresh" button in the revitalizer UI

### ISSUE THREAD

**Issue by uniwars** [robinsving/pf2e-item-revitalizer#18]
Hi, would that be possible to directly add the refresh button from an item next to it in the revitalizer UI ?
Like that : 
![image](https://github.com/robinsving/pf2e-item-revitalizer/assets/65986545/ea471191-e840-4495-8b5f-f07010dcb8f1)

Also it would be nice if after pressing the refresh button like that the line was greyed off or marked as updated to know what we need to refresh and what we already refreshed on the list.

**Comment by uniwars** [comment]
Just thinking, could a refresh all button be added ? It would refresh all item with an active refresh button (some have it greyed out because they can't be refreshed, like feat with selector)

**Comment by robinsving** [comment]
Hi Uniwars. That "refresh" button is not a part of the PIR-module. It is a feature of the PF2e system itself.
I have not found a good way to determine if the item is "refreshable" according to the PF2e system (which means that I don't know if it should be greyed out). Unless I have misunderstood something, this is not a request for me, but for the PF2e system devs.

Concerning the other request, I have a wish in the future to do this, but it is a scary thing to have available. My thinking is to add tabs to the result popup, and then have a "revitalize all" on a more granular scale.

Btw, love that theme of yours!

**Comment by uniwars** [comment]
Hi, I knew the refresh button is part of the system and that's why I asked if it could be possible to integrate it in revitalizer.
I saw that there is a setting in the module to "revitalize" from the revitalizer UI but there is a very cocnerning warning for me (I have 40+ players and I don't want to investigate if someone broke its sheet) and as far as I know there isn't such warning with the system refresh button.
If I understood it right only item wich selector RE cannot be refreshed by the system so by excluding selector it should works I guess

**Comment by robinsving** [comment]
Revitalizer works by only refreshing properties that are *safe*, meaning that it can handle more cases than the Refresh.
Note that I have yet to break a single sheet with PIR; it is more of a cautionary warning at this point as I don't know all of the states that players may do to items :)

Perhaps I will take a look at the PF2e code in the future, as there may be an easy way to do what you suggest - and if it is only ignoring certain types of REs, then it should indeed be easy - but that is not the the plans currently.

**Comment by robinsving** [comment]
Version 1.22.1 now allows the usage of PF2e Refresh button from within PIR
