### ISSUE TITLE
Feature Request: one button full refresh of all items after refresh menu pops up

### ISSUE THREAD

**Issue by GuitarGuyNick** [robinsving/pf2e-item-revitalizer#20]
when you click revitalise on the menu on a sheet for npc or pc. it would be nice to have a refresh all button that goes through them one after the other without having to click the refresh button 200 times.

**Comment by robinsving** [comment]
I have been hesitant to add such a thing, as it causes a higher risk of having something bad happen to your items. But I have been getting this request more than once, so perhaps I will look into it next time I have time to work on this module

**Comment by GuitarGuyNick** [comment]
if it could be marked as experimental with the explanation you gave above. then its on the users to have that responsibility. im ok with what it may do.

**Comment by robinsving** [comment]
Hi Nick

I have taken a look at this feature request, and there is a problem with my templating framework (handlebars) when it comes to data manipulation in conjunction with Foundry's Dialog (which displays the Results-page ).

The issue becomes this: once the Results-page shows up, then there is a set list of items on that page. It is not data-bound - instead, it is HTML generated from the input. This means that such a feature would not be able to take into consideration if a user has already removed an Item using Hide/Remove buttons - _it would still Refresh the removed things_.

I cannot see a way to do this feature request without changing my whole templating setup, or opting out of Foundry's built-ins, unfortunately :(
