### ISSUE TITLE
Refreshing At Will spells on NPC changes them to not have the (At Will) descriptor)

### ISSUE THREAD

**Issue by soch0601** [robinsving/pf2e-item-revitalizer#21]
When I clicked my Poltergeist to do a revitalize, it had me change Telekinetic Maneuver because the spell was the old version.

After refresh, it no longer had the "At Will" designation.

After Refresh:
![image](https://github.com/robinsving/pf2e-item-revitalizer/assets/58669889/80f62c62-971a-47e1-b49e-97f7e28f63c0)

Direct from the beastiary:
![image](https://github.com/robinsving/pf2e-item-revitalizer/assets/58669889/c763e6cd-0143-4ed8-a730-6452cb484ab6)

An example of a different creatures spell prior to refresh (name hidden to prevent spoilers):
![image](https://github.com/robinsving/pf2e-item-revitalizer/assets/58669889/2a0b1477-48ca-4b93-a3cc-56a754dbcb3d)

Note, clicking the left-most button in the line to refresh it does this.  Let me know if I need to go bug the pf2e team about this (and if you have a github link to report to I would also appreciate that).

Thanks!

**Comment by robinsving** [comment]
Thanks for reaching out. The circular shape of the refresh button is indeed the built-in Refresh tool from the PF2e system, so this needs to go to them.

I am on vacation, so I don't have a link available,  but it should be a repo called pf2e on foundry's github

**Comment by soch0601** [comment]
Got it, reported it here:
https://github.com/foundryvtt/pf2e/issues/13926

Thanks!

**Comment by soch0601** [comment]
In the pf2e reported issue, they suggested this module have some sort of feature to add - Either a name preservation, or potentially detecting the '(At Will)' string and adding it back.  Would you be willing to add a feature like that?

Also, enjoy your vacation, can discuss this once you are back home!

**Comment by robinsving** [comment]
Should be possible to determine if a name should be updated by matching some criteria. "(At Will)" is specific, ans may be the best solution. But I do wonder if the existence of parenthesis, may be a good option as well. Will have a look when I am back

**Comment by robinsving** [comment]
New version should have this fixed. Decided on just handling "(At Will)" in the name. Hopefully there are not that many other things I miss

**Comment by soch0601** [comment]
Confirmed that this is now working as expected.  Thanks!

And don't worry - I will keep on testing stuff and if I find anything else I will let you know!
