### ISSUE TITLE
Remove bar button from NPC sheet

### ISSUE THREAD

**Issue by uniwars** [robinsving/pf2e-item-revitalizer#24]
Hi, would that be possible to remove or just keep the icon from the NPC sheet ?

![image](https://github.com/user-attachments/assets/195a8b4c-9292-43ed-9900-c85d34f61cea)

there are soe many things in there that I can't see "close" anymore without expanding the sheet

**Comment by robinsving** [comment]
I see the issue. Will be fixed in 1.28.0

**Comment by robinsving** [comment]
You can try it out now. Note that you can still use the Revitalization feature from the Actors' tab to Revitalize an NPC, should you need to
