### ISSUE TITLE
Revitalize Button no longer works

### ISSUE THREAD

**Issue by dharkus5000** [robinsving/pf2e-item-revitalizer#25]
When i tried this on the 1st PC in my Party, i clicked the button and nothing happened apart from the msg that it might take a few minutes, i checked the console 15m later and saw an error
`Uncaught (in promise) TypeError: JSON.stringify(...) is undefined
[Detected 1 package: pf2e-item-revitalizer(1.28.0)]
    getDifferentiatingProperties_fn RevitalizerCalculator.js:160
    compareItems_fn RevitalizerCalculator.js:230
    runRevitalizerCheck RevitalizerCalculator.js:300
RevitalizerCalculator.js:160:35`

also, I just went out then back in cause i thought to check other PCs
the same PC as i tried before, a Magus, now gives a different error msg
`Uncaught (in promise) TypeError: JSON.stringify(...) is undefined
[Detected 2 packages: pf2e-item-revitalizer(1.28.0), system:pf2e(6.7.0)]
    getDifferentiatingProperties_fn RevitalizerCalculator.js:160
    compareItems_fn RevitalizerCalculator.js:230
    runRevitalizerCheck RevitalizerCalculator.js:300
    runRevitalizerCheckForActors_fn RevitalizerRunner.js:110
    revitalizerCheckForActorIds_fn RevitalizerRunner.js:80
    RevitalizerRunner RevitalizerRunner.js:23
    #call foundry.js:632
    call foundry.js:614
    registerHook_fn RevitalizerSheet.js:87
    jQuery 9
    registerHook_fn RevitalizerSheet.js:87
    #call foundry.js:632
    callAll foundry.js:589
    _callHooks foundry.js:5918
    _render foundry.js:5879
    _render foundry.js:6572
    _render foundry.js:7158
    _render pf2e.mjs:1341
    maintainFocusInRender pf2e.mjs:1341
    _render pf2e.mjs:1341
    render foundry.js:5793
    _onClickEntryName foundry.js:73976
    jQuery 2
RevitalizerCalculator.js:160:35`

the other 3 PCs in the Party worked fine with no problems - i can share the .json of the Magus if that'd be helpful

**Comment by robinsving** [comment]
It is possible that there is an Item that either is not handled properly by the mod, or that is not a proper Item. Sharing the Actor would help immensely.

Also, I should probably add an error popup if the Revitalization calculation fails :)

**Comment by dharkus5000** [comment]
[fvtt-Actor-arbal-oOV3NIPPiKhfTzz7.json](https://github.com/user-attachments/files/17850090/fvtt-Actor-arbal-oOV3NIPPiKhfTzz7.json)

**Comment by robinsving** [comment]
Thanks for sending it in.

The 1.28.1 bugfix version should work for you. Please confirm

**Comment by dharkus5000** [comment]
yep, working now

**Comment by robinsving** [comment]
Great, closing this
